let s = `KCIBALHMDDEJMBLOOFINNOGCPCHLHBAONHAKKIFAFGJGL
PMAAMAIOIEOOMIPIGBCFMGBAACCJAHAEJOPFOGGKIIMANEIBFABMFCNDPNF
HDGCBBLOAKAKHFINACODKDGKNCAIKIHKCFKCKKBHIMEADPEAPBADOFHEHAH
AHFACNLHCMIHHHOFCMENKDHIGNNLBAAJJMEJFMHMMCHEMDADIMEAKPEIPPG
ACAFAHONMEECONLMGJAKAPDPIHNIFCBCHLFMNCMECDMHHGHIOFOAIHNAAAJ
CJHNCHFAMJCFGEMCMCHHMCNAHJOOIFKGHIBLDPEOAEBNGAALAAHEOKJKFIN
IHGDBDHJOCDACHHEAAHKFHIGIKHPMMCLPCEMCOCKNEMIOAOOMEAKCACDHAD
NFMGNNACHAHFCMKLGNHANKIFDFFPHLABMHAFLOIAMGDCLFDEKHAHBMEACHG
HPPGCNHOHBMENCMCHMIGDMFEGEOIBOBKILCPMPFAHCEBAJJOKICLDFEAJFB
MLAAPAEGBDJDKPCKKIMNNEKOPFLPAOPMEAJPHAPKJDLJAKNJAANFOHKEPJO
AOAOAAIFIDAPEFJFKHIPNAFONPNNGCNHAHAHKIFFOCHNALOBNCOCNAHKPHI
LCCCIFNGADHANEAAJDMPBKKKNAAIKENIMDCFFAKJBCHIAHJJKACKGAIAPKI
EHIAHGICBPDKHKCHIFCPMPMKGKMDEIEOPAAJJKEBLMMKCGAJIFCPGOEGLPA
EADOIJNIHALFNHENFAOAAGNEHOMAABOAMAMBNECJDHGICPHNOACEBNADCAK
IOLHOCONONHDKCDOPPGNACAMOIKAFNJOBCGDNCOCNAHKBJIEPABOFNGLDHA
KHEIFJMFKHAHFHFAKCJIMAFKCKMIPAACFDDAJOPDFANJAONAOBEIGIFBLOA
IEJPAADFAJNAKFKCIBHHHOOMIHMIEMKHIAFAFOKJNMDAFPHFFNMCGONDOAI
LBGOMIOAACMOMCBCFENDMHAFGEACIABNADEFCGMNAHOJDIHEIHFMDEHDPPC
BPHHANIBMICGOIENCKOLECIBKDIEKIDAIFAEEGMJKKIDHFICHCHKCFPHMBE
COONAHMJFJECNEEJBOIBACPAFMBAEENOFDHAOIBICIEBHAEAGAJJDAGHMLC
HMNCAIMEKAMFJCHFJDDFHIOIAKIMILFDMCOAINHFAADAAEPHJKDKEDKIKMA
JELOJNDCKHHNOINHLAIKDDHDMPAKKEFGFNIBCPNDKDMAJIKNOIOIBBPKKKC
AAIKPGIICBDEOONBCHOKDBIKOOLOANJDHFAOKEIPAJEHANAKEBGHICLDHHG
FFMGFAJCOBCINBOOKFOGJFGOFFAMBCFLEBOPIAAEDADLGJFACMKCFAAIOBG
OLOPIHMMCFDEEFFLGIDBJHEDBLHFPDDCPHDHEKFACCOIACLDDFCMCHFFBJK
CIBALHMDDEJMBLOOFINNOGCPCHLHBAONHAKKIFAFGJGLPMAAMAIOIEOOMIP
IGBCFMGBAACCJAHAEJOPFOGGKIIMANEIBFABMFCNDPNFHDGCBBLOAKAKHFI
NACODKDGKNCAIKIHKCFKCKKBHIMEADPEAPBADOFHEHAHAHFACNLHCMIHHHO
FCMENKDHIGNNLBAAJJMEJFMHMMCHEMDADIMEAKPEIPPGACAFAHONMEECONL
MGJAKAPDPIHNIFCBCHLFMNCMECDMHHGHIOFOAIHNAAAJCJHNCHFAMJCFGEM
CMCHHMCNAHJOOIFKGHIBLDPEOAEBNGAALAAHEOKJKFINIHGDBDHJOCDACHH
EAAHKFHIGIKHPMMCLPCEMCOCKNEMIOAOOMEAKCACDHADNFMGNNACHAHFCMK
LGNHANKIFDFFPHLABMHAFLOIAMGDCLFDEKHAHBMEACHGHPPGCNHOHBMENCM
CHMIGDMFEGEOIBOBKILCPMPFAHCEBAJJOKICLDFEAJFBMLAAPAEGBDJDKPC
KKIMNNEKOPFLPAOPMEAJPHAPKJDLJAKNJAANFOHKEPJOAOAOAAIFIDAPEFJ
FKHIPNAFONPNNGCNHAHAHKIFFOCHNALOBNCOCNAHKPHILCCCIFNGADHANEA
AJDMPBKKKNAAIKENIMDCFFAKJBCHIAHJJKACKGAIAPKIEHIAHGICBPDKHKC
HIFCPMPMKGKMDEIEOPAAJJKEBLMMKCGAJIFCPGOEGLPAEADOIJNIHALFNHE
NFAOAAGNEHOMAABOAMAMBNECJDHGICPHNOACEBNADCAKIOLHOCONONHDKCD
OPPGNACAMOIKAFNJOBCGDNCOCNAHKBJIEPABOFNGLDHAKHEIFJMFKHAHFHF
AKCJIMAFKCKMIPAACFDDAJOPDFANJAONAOBEIGIFBLOAIEJPAADFAJNAKFK
CIBHHHOOMIHMIEMKHIAFAFOKJNMDAFPHFFNMCGONDOAILBGOMIOAACMOMCB
CFENDMHAFGEACIABNADEFCGMNAHOJDIHEIHFMDEHDPPCBPHHANIBMICGOIE
NCKOLECIBKDIEKIDAIFAEEGMJKKIDHFICHCHKCFPHMBECOONAHMJFJECNEE
JBOIBACPAFMBAEENOFDHAOIBICIEBHAEAGAJJDAGHMLCHMNCAIMEKAMFJCH
FJDDFHIOIAKIMILFDMCOAINHFAADAAEPHJKDKEDKIKMAJELOJNDCKHHNOIN
HLAIKDDHDMPAKKEFGFNIBCPNDKDMAJIKNOIOIBBPKKKCAAIKPGIICBDEOON
BCHOKDBIKOOLOANJDHFAOKEIPAJEHANAKEBGHICLDHHGFFMGFAJCOBCINBO
OKFOGJFGOFFAMBCFLEBOPIAAEDADLGJFACMKCFAAIOBGOLOPIHMMCFDEEFF
LGIDBJHEDBLHFPDDCPHDHEKFACCOIACLDDFCMCHFFBJPOBAPFAJDIFMFKGG
OEIAPAALJIOBOJNKMCPNIDAPCBEKKFIMAAGBOFNCJFNENAOMMEAKGNIMCBM
CCFHHAJGKGOIBBGPMAFJPDPNONAOFCKMMCACMJPACIHHPMEDJOFOGNAAAEE
ANDAPNNNOHNOAAMJAAMBHLFMGHHFCNCDALHHICDOHHHFIMLFHEIOCFKHIEA
AFMNHECKONIKAIKAJJMNDEEEBAFNAAGAAJKEFKLPMILOJNIDPPMMLEIBCHM
MOEDAJIAMGALMPHPANAMFAACHGKBGNPHKOIDKINDHFHGJAKDCHHPAAHKHDI
KOBCJFNGMMEOOPKIGAALHHKFPCHINAKAEAKPDEOBFAJIAIEAOLCGLCKHCNO
INFMAEJILFMDEDKKPILPEJHMDKAOADAAIMICCBEADFOFNCKIANEOANAFIAM
OEBAJIDNNHGNAKKOMIPAACMDDCLNOFEDMHCFGEADAADIOCGKKIGHFICDHHM
IGPEMBEAOONAHMJJHAFFNEGPOIBAIGALMJGJAKJHJKIFAPGPLGPPDKPLCHI
FKNNMAAMINNAAAAOKPHCCHNMDFMGMMECHALFKCFBIOAIJNAAAMBAMPEHLHF
HCHFMKCBIMPPECMAEHDPJAFOJFMHBDAMAMOIEHEMHOFPPCANJEDPAKAPIEK
BLGMACKHFAFCPGEALOIOKIHCHIFFIGCPPMJFDNDMEPMHNCHCBCJNHAMFGFA
HNANDBPICKHNNOINHBAGDCGIMDEMKKPIMGEMPHELHAHHEJACFIHEHDJKFOA
JKIIHCKFMNKHAMOCDKINFKCGMMKCDANADHFAMOMCHEDNFFMGHOICMFMEHJA
APHAFFDHAKKNIACFLAOCOJKIHBAENNAJJHOAIHMEJEGOBFOJEMAOAFAAINP
MOJEFJCNCABKIHKHCKADEHDFDNAMEPAEFJJEDIJKDIEKIDACIAMMPKIKKIN
KIKCBPHENBAIKOIMOONHKJFDPAFHOAIINAJEPABGGHMDNAAKAAJACJALGDF
FHNFHFAAKCHIGHHKBCNKCONAANJAMEDMOKCIDHHHDHAHEJFDLDEPKFMOMMN
EAFNJFKAIPAJJMKFCGGGNDAOABFGIKLKIECKKCDOEJMCOMHIEBGCCKHFFPM
CGDEBPKLGBPODIDEBPAEKAAGKIAMKECHFIADGJBANDBMFEHAJMAJDALLPEP
MCEJHHHOMPNNDMDHNFAGMCGHCAFFKKJMMFENOIGDFHPCIMAMFMGPFNCHLLF
CINAEOAEBNAABOCPOLPFDHAFKDLAANGAIDMONMKCAMCIFAFGKADFOMHEFNA
FAPHABJDENKNIMKIODCNPGDBJCCADCKIAHCMPBFPLKAJANJAACAKCFDAAKF
KGFDPIMJICOPDAGCOKHNOIAGLAAJBGKDKHBNOINKBADFANEOOIGAJNCBNHF
LDAPNHGCKIFABNAIMHPNAKAKOEIHBMFODEJFCKHJFGIKABIBKHODHAHHIEA
KPAIEGHJHHKFMDPIOIKIMDAEDAMAEAJECCFDCGBADFABIOFGAHEAGCBCCAN
AHDDGCNGHPGDFPKNIAOOOHNFFEHFMPMOCCKINFJKGAIFLEAKACHFIBBBMEL
GIIMHEJKIFFDJGHPPAPKNIMMCODGFDJHMBOBAMKKIAKJCIDFOLGNFAEJPAA
OCADMCNDOCIIHHHABEJJJHGHKDIPEBPAHFACNEJOEMOCCHEMPMEEBNMMMOE
GAJIABAAECLMEMACIKIAFFHGFNCCEOKIACHIFMNGMMBBFFDNOMEPMONCGPA
FIMHEGFGFAILAKKKJBDKPMKKIFEDNFKOIHDKDMEOIKHMIBBIJLNKOJAAIMF
BEJKFHKMACKNAJNILOAJIJGKDIGKIDAMCAFPGLIKDIBCCPFJKGIGCLCMACD
NAAAIAABIGDJKKIAMCIFAFGJFKHOFMGPHFEMABCCECANOHOBFGFJCBPJMPG
DDOHCDEIAGPACEGPJKKIKHFICAMHEKNOGMBEIOONAHFJOFAGGDMHKOIENMP
GAEJOIAOAJAAEACDJKEACMHOFCNANKENIHKLJCKAIIONJDPDHKHMDOKNIIA
AOCGAHHCIIEDKPCNAKMEHEJMNNJCFHOMCGKBIIEOCJFOAIAMEJOHLIKGIFD
MKCFAAIAFEJMFENGAHJEKIFKMMIPNKEMOAONIEAHIMHDNNMBACAMKIHOMFN
IFKJDNDACMEPDBJPHEINLAEANMCBALKJKPMCOMACMNAAFAMGCEMJPOKICCH
IFKKGFBCLIFDNMMEPMNGCLIFABKHIAFGFABBAIOEGJCKHANOINHEAMLKJAM
DEJKKPIDCEDHHKPKOICAANAPKACMGMIDMHBIHCONDIPDJIHNPAEAJCAKFAH
CCNPDNPKHFOJJAPFAPDFFOGAKCIMGAEFIGINAFJNDPNKGGIPHNEAHAHEEJA
CKHHMMPKOIAHBOIAFALGKOBGNADAPKIHHPAFJCFPENFAKAAGNPEONECELNO
OAFGIKFHIFABHOMFEGLDGCADKGGIJGKOCOAJIMEIEBHMJNONIEMCOMFMEEL
DHMNFAIAAAOLLNIFNAJOAIMNAJEJPBMNNKINAAFAAJAHHAJDJDIAKJANOIM
CKCKGFEAOCOIFGHOEKIFACGDHKFCCHINDFABGIDLMOEGAJIAIJAKMNOEDNP
CHFOJBAPGDAJJDNPDKCAOINIBDEBAAFAHMCNFHBGEFAGHKMKJCHEKPJIDKK
POANJHHFAOCFILMJLJHAFBEBAKKOIBEAENKDIBFAHBABNJMIHOMKCPAJIFA
OGIBMLJHAHJOIACPBHJEKFKDHPMOIFMHNEIPEDEAMJDKCEOKFIEAALHAFKE
BAMKJCMCDNIACAMMEKNOGOGMGIDMNCIDPAMABCIKLGHAHAAKIFNODOKEOBB
NCANKIHKBPKNNEJMIMEADPEABEAIEGGHEDBAONPAJNAAOMMLIMEPONEMMMC
OCKJCOHIOFGFINDEDIFFOAHAPAAFKFPILKNOANMAHNOEAKHJKNEEBMNBBME
MICBABBOBMMBLMBBMFCBCBFAI`;

let arr = [];
    let a = 32;
    for (let i = 0; i < s.length; i++) {
        if (a === 32) {
            arr.push(s.slice(i, i + 32));
            a = 0;
        }
        a += 1;
    }

let shifts = {
    0 : [2, 0],
    1 : [6, 1],
    2 : [5, 4],
    3 : [10, 7],
    4 : [18, 16],
    5 : [21, 20],
    6 : [22, 17],
    7 : [26, 23],
};

window.onload = function() {
let pairs = {};
for (let i = 0; i < shifts.length; i++) {
  for (let el of arr) {
    pairs[`${el[shifts[i][0]]}${el[shifts[i][1]]}`] = 0;
  }
}

for (let i = 0; i < shifts.length; i++) {
  for (let el of arr) {
    pairs[`${el[shifts[i][0]]}${el[shifts[i][1]]}`] += 1;
  }
}

let total = 0;
for (let pair in pairs) {
  total += pairs[pair];
}
let result = [];
for (let pair in pairs) {
  result.push(`${pair} = ${(pairs[pair] / total * 100).toFixed(2)}%`);
}
console.log(result);
}